# Generated by Django 4.2.15 on 2026-09-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0008_session_sessionattendance_event_meeting_event_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriveResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[("folder", "Folder"), ("file", "File")], max_length=50
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=255, unique=True)),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drive_resources",
                        to="meetings.meeting",
                    ),
                ),
            ],
        ),
    ]
