# Generated by Django 4.2.15 on 2026-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentorder",
            name="instrument_code",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="paymentorder",
            name="process_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
