# Generated by Django 4.2.15 on 2026-08-26 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0002_meetingpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                (
                    "storage_type",
                    models.CharField(
                        choices=[
                            ("drive", "Google Drive"),
                            ("s3", "AWS S3"),
                            ("gcs", "Google Cloud Storage"),
                        ],
                        default="drive",
                        max_length=50,
                    ),
                ),
                (
                    "storage_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("storage_size_mb", models.FloatField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("recording", "Recording"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="recording",
                        max_length=20,
                    ),
                ),
                ("video_format", models.CharField(default="mp4", max_length=20)),
                ("bitrate_kbps", models.IntegerField(default=2500)),
                ("resolution", models.CharField(default="1080p", max_length=20)),
                (
                    "download_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("stream_url", models.URLField(blank=True, max_length=1000, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "recordings",
                "indexes": [
                    models.Index(
                        fields=["meeting", "status"],
                        name="recordings_meeting_f7cbd9_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="recordings_created_3645f5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_participants", models.IntegerField(default=0)),
                ("peak_participants", models.IntegerField(default=0)),
                ("total_duration_seconds", models.IntegerField(default=0)),
                ("active_duration_seconds", models.IntegerField(default=0)),
                ("messages_count", models.IntegerField(default=0)),
                ("screen_shares_count", models.IntegerField(default=0)),
                ("recordings_count", models.IntegerField(default=0)),
                ("avg_latency_ms", models.FloatField(default=0)),
                ("packet_loss_percent", models.FloatField(default=0)),
                ("bandwidth_used_mb", models.FloatField(default=0)),
                (
                    "participant_engagement_score",
                    models.FloatField(default=0, help_text="0-100"),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_analytics",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="meeting_ana_created_8fb70d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("participant_id", models.CharField(max_length=255)),
                ("participant_name", models.CharField(max_length=255)),
                (
                    "participant_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("joined_at", models.DateTimeField()),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "indexes": [
                    models.Index(
                        fields=["meeting", "joined_at"],
                        name="attendance_meeting_026718_idx",
                    )
                ],
            },
        ),
    ]
