# Generated by Django 4.2.15 on 2026-09-17 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_text", models.TextField(blank=True)),
                ("word_count", models.IntegerField(default=0)),
                (
                    "drive_file_id",
                    models.CharField(
                        blank=True,
                        help_text="Google Docs file ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="meetings.event",
                    ),
                ),
            ],
            options={
                "db_table": "transcripts",
            },
        ),
        migrations.CreateModel(
            name="TranscriptSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary_text", models.TextField()),
                (
                    "key_points",
                    models.JSONField(
                        default=list, help_text="List of key discussion points"
                    ),
                ),
                (
                    "action_items",
                    models.JSONField(
                        default=list, help_text="List of action items with owner"
                    ),
                ),
                (
                    "attendee_summary",
                    models.JSONField(
                        default=dict,
                        help_text="Summary per attendee (contributions, key points)",
                    ),
                ),
                (
                    "llm_provider",
                    models.CharField(
                        default="pending",
                        help_text="LLM used (claude, openai, etc)",
                        max_length=50,
                    ),
                ),
                ("llm_model", models.CharField(blank=True, max_length=100)),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "drive_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error if summarization failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="meetings.event",
                    ),
                ),
                (
                    "transcript",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="transcription.transcript",
                    ),
                ),
            ],
            options={
                "db_table": "transcript_summaries",
                "indexes": [
                    models.Index(
                        fields=["event", "is_complete"],
                        name="transcript__event_i_ac8a87_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TranscriptionSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "speaker_id",
                    models.CharField(
                        help_text="Participant session ID", max_length=255
                    ),
                ),
                (
                    "speaker_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("text", models.TextField()),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "start_time",
                    models.FloatField(help_text="Start time in the event (seconds)"),
                ),
                (
                    "end_time",
                    models.FloatField(help_text="End time in the event (seconds)"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0, help_text="Speech recognition confidence 0-1"
                    ),
                ),
                (
                    "is_final",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is final or interim transcript",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcription_segments",
                        to="meetings.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcription_segments",
                        to="meetings.session",
                    ),
                ),
            ],
            options={
                "db_table": "transcription_segments",
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"],
                        name="transcripti_event_i_bc5671_idx",
                    ),
                    models.Index(
                        fields=["event", "start_time"],
                        name="transcripti_event_i_b93fa5_idx",
                    ),
                    models.Index(
                        fields=["is_final"], name="transcripti_is_fina_a570f0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="transcript",
            index=models.Index(
                fields=["event", "is_complete"], name="transcripts_event_i_6eef9f_idx"
            ),
        ),
    ]
