# Generated by Django 4.2.15 on 2026-09-03 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0008_session_sessionattendance_event_meeting_event_and_more"),
        ("transcription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transcriptionsegment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transcription_segments",
                to="meetings.session",
            ),
        ),
    ]
