# Generated by Django 4.2.15 on 2026-09-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                ("drive_folder_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_folders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_folders",
                        to="meetings.event",
                    ),
                ),
            ],
            options={
                "db_table": "photo_folders",
                "ordering": ["-is_default", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("web_view_link", models.URLField(blank=True, max_length=800)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="meetings.event",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="artifacts.photofolder",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_photos",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("folder", "Folder"),
                            ("metadata", "Metadata"),
                            ("transcript", "Transcript"),
                            ("attendance", "Attendance"),
                            ("notes", "Notes"),
                            ("resource", "Shared Resource"),
                            ("recording", "Recording"),
                            ("summary", "Event summary"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("now", "Visible now"),
                            ("after_session", "After the session"),
                            ("public", "Public to all"),
                            ("organizers", "Organizers only"),
                        ],
                        default="after_session",
                        help_text="Who may read this file, and from when",
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "drive_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "web_view_link",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="meetings.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="artifacts",
                        to="meetings.session",
                    ),
                ),
            ],
            options={
                "db_table": "artifacts",
            },
        ),
        migrations.AddConstraint(
            model_name="photofolder",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="one_photo_folder_per_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="photofolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("event",),
                name="one_default_photo_folder_per_event",
            ),
        ),
        migrations.AddIndex(
            model_name="eventphoto",
            index=models.Index(fields=["event"], name="event_photo_event_i_8b0ae6_idx"),
        ),
        migrations.AddIndex(
            model_name="eventphoto",
            index=models.Index(
                fields=["folder"], name="event_photo_folder__c78aad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["event", "artifact_type"], name="artifacts_event_i_0e233e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["drive_file_id"], name="artifacts_drive_f_c9463a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["sync_status"], name="artifacts_sync_st_879950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["event", "sync_status"], name="artifacts_event_i_ee8b04_idx"
            ),
        ),
    ]
