# Generated by Django 4.2.3 on 2026-08-26 06:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[
                            ("folder", "Folder"),
                            ("metadata", "Metadata"),
                            ("transcript", "Transcript"),
                            ("attendance", "Attendance"),
                            ("notes", "Notes"),
                            ("resource", "Shared Resource"),
                            ("recording", "Recording"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "drive_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "artifacts",
                "indexes": [
                    models.Index(
                        fields=["meeting"], name="artifacts_meeting_c4821f_idx"
                    ),
                    models.Index(
                        fields=["artifact_type"], name="artifacts_artifac_d86ab0_idx"
                    ),
                    models.Index(
                        fields=["drive_file_id"], name="artifacts_drive_f_c9463a_idx"
                    ),
                ],
            },
        ),
    ]
