# Generated by Django 4.2.15 on 2026-09-30 11:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photofolder",
            options={"ordering": ["created_at"]},
        ),
    ]
