# Generated by Django 4.2.15 on 2026-08-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="artifact",
            name="artifacts_meeting_c4821f_idx",
        ),
        migrations.RemoveIndex(
            model_name="artifact",
            name="artifacts_artifac_d86ab0_idx",
        ),
        migrations.AddField(
            model_name="artifact",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="last_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="artifact",
            name="retry_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artifact",
            name="sync_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("syncing", "Syncing"),
                    ("synced", "Synced"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="artifact",
            name="synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artifact",
            name="web_view_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="artifact",
            name="artifact_type",
            field=models.CharField(
                choices=[
                    ("folder", "Folder"),
                    ("metadata", "Metadata"),
                    ("transcript", "Transcript"),
                    ("attendance", "Attendance"),
                    ("notes", "Notes"),
                    ("resource", "Shared Resource"),
                    ("recording", "Recording"),
                    ("summary", "Meeting Summary"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["meeting", "artifact_type"], name="artifacts_meeting_88b9ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["sync_status"], name="artifacts_sync_st_879950_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="artifact",
            index=models.Index(
                fields=["meeting", "sync_status"], name="artifacts_meeting_61f1c7_idx"
            ),
        ),
    ]
