# Generated by Django 4.2.15 on 2026-10-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0003_retire_the_default_photo_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artifact",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("now", "Visible now"),
                    ("after_session", "After the session"),
                    ("public", "Public to all"),
                    ("organizers", "Organizers only"),
                ],
                default="now",
                help_text="Who may read this file, and from when",
                max_length=20,
            ),
        ),
    ]
