# Generated by Django 4.2.15 on 2026-09-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("artifacts", "0003_artifact_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="artifact",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="artifact",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("now", "Visible now"),
                    ("after_session", "After the session"),
                    ("public", "Public to all"),
                    ("organizers", "Organizers only"),
                ],
                default="after_session",
                help_text="Who may read this file, and from when",
                max_length=20,
            ),
        ),
    ]
