# Generated by Django 4.2.15 on 2026-09-08 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0017_reminders"),
        ("artifacts", "0004_resource_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                ("drive_folder_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_folders_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo_folders",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "photo_folders",
                "ordering": ["-is_default", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("drive_file_id", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("web_view_link", models.URLField(blank=True, max_length=800)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="artifacts.photofolder",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_photos",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="photofolder",
            constraint=models.UniqueConstraint(
                fields=("meeting", "name"), name="one_photo_folder_per_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="photofolder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("meeting",),
                name="one_default_photo_folder_per_meeting",
            ),
        ),
        migrations.AddIndex(
            model_name="meetingphoto",
            index=models.Index(
                fields=["meeting"], name="meeting_pho_meeting_c6f905_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingphoto",
            index=models.Index(
                fields=["folder"], name="meeting_pho_folder__21b6f2_idx"
            ),
        ),
    ]
