# Generated by Django 4.2.15 on 2026-08-26 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleConnectionScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scope", models.CharField(max_length=500)),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scope_grants",
                        to="accounts.googleconnection",
                    ),
                ),
            ],
            options={
                "db_table": "google_connection_scopes",
                "indexes": [
                    models.Index(
                        fields=["connection", "is_revoked"],
                        name="google_conn_connect_cce24b_idx",
                    )
                ],
                "unique_together": {("connection", "scope")},
            },
        ),
    ]
