# Generated by Django 4.2.15 on 2026-09-17 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hostaccount",
            old_name="meeting_reminder_minutes",
            new_name="event_reminder_minutes",
        ),
    ]
