# Generated by Django 4.2.15 on 2026-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0002_rename_meeting_reminder_minutes_hostaccount_event_reminder_minutes",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
