# Generated by Django 4.2.15 on 2026-09-05 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def grant_host_standing(apps, schema_editor):
    """Anyone already running something is a host — say so explicitly.

    Host standing used to be implied by owning an event or a meeting. Now it
    lives in a row, so the people who earned it before this migration need
    one, on the free plan they have effectively been using.
    """
    HostAccount = apps.get_model('accounts', 'HostAccount')
    Event = apps.get_model('meetings', 'Event')
    Meeting = apps.get_model('meetings', 'Meeting')

    owners = set(Event.objects.values_list('organizer_id', flat=True))
    owners |= set(Meeting.objects.values_list('host_id', flat=True))
    owners.discard(None)

    HostAccount.objects.bulk_create(
        [HostAccount(user_id=owner, plan='free', status='trial') for owner in owners],
        ignore_conflicts=True,
    )


def revoke_host_standing(apps, schema_editor):
    apps.get_model('accounts', 'HostAccount').objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ('meetings', '0010_session_speaker_email_session_speaker_phone_and_more'),
        ("accounts", "0002_googleconnectionscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="HostAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("starter", "Starter"),
                            ("growth", "Growth"),
                            ("business", "Business"),
                            ("enterprise", "Enterprise"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trial", "Trial"),
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="trial",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "host_accounts",
            },
        ),
        migrations.RunPython(grant_host_standing, revoke_host_standing),
    ]
