# Generated by Django 4.2.15 on 2026-09-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_host_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpgradeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan", models.CharField(max_length=20)),
                ("from_plan", models.CharField(blank=True, max_length=20)),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("asked", "Asked"),
                            ("done", "Applied"),
                            ("declined", "Declined"),
                        ],
                        default="asked",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrade_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upgrade_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="upgraderequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "asked")),
                fields=("user", "plan"),
                name="one_open_upgrade_request_per_plan",
            ),
        ),
    ]
