# Generated by Django 4.2.15 on 2026-09-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_organization_name_user_phone_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="billing_address",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
