# Generated by Django 4.2.15 on 2026-09-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_upgrade_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostaccount",
            name="session_gap_minutes",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
