# Generated by Django 4.2.15 on 2026-09-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_hostaccount_session_gap_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostaccount",
            name="meeting_reminder_minutes",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="hostaccount",
            name="reminders_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="hostaccount",
            name="session_reminder_minutes",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
