# Generated by Django 4.2.15 on 2026-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_user_deletion_requested_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostaccount",
            name="idle_timeout_minutes",
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
