# Generated by Django 4.2.15 on 2026-09-29 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_hostaccount_idle_timeout_minutes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPrefs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_reminders", models.BooleanField(default=True)),
                ("new_sessions", models.BooleanField(default=True)),
                ("event_updates", models.BooleanField(default=True)),
                ("new_files", models.BooleanField(default=True)),
                ("published_summaries", models.BooleanField(default=True)),
                ("email_event_reminders", models.BooleanField(default=True)),
                ("email_event_updates", models.BooleanField(default=False)),
                ("email_weekly_digest", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_prefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_prefs",
            },
        ),
    ]
