# Generated by Django 4.2.15 on 2026-10-01 12:10

from django.db import migrations, models
import src.apps.accounts.models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_notificationprefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to=src.apps.accounts.models.avatar_path
            ),
        ),
    ]
