# Generated by Django 4.2.15 on 2026-08-26 07:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("meetings", "0002_meetingpermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("concurrent_meetings", "Concurrent Meetings"),
                            ("concurrent_participants", "Concurrent Participants"),
                            ("api_response_time", "API Response Time"),
                            ("websocket_messages", "WebSocket Messages"),
                            ("celery_task_time", "Celery Task Time"),
                            ("drive_api_calls", "Drive API Calls"),
                            ("speech_api_calls", "Speech API Calls"),
                        ],
                        max_length=50,
                    ),
                ),
                ("metric_value", models.FloatField()),
                (
                    "labels",
                    models.JSONField(
                        default=dict,
                        help_text="Additional dimensions (endpoint, worker, etc)",
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "system_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_type", "recorded_at"],
                        name="system_metr_metric__fcce09_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MeetingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meeting_created", "Meeting Created"),
                            ("meeting_started", "Meeting Started"),
                            ("meeting_ended", "Meeting Ended"),
                            ("participant_joined", "Participant Joined"),
                            ("participant_left", "Participant Left"),
                            ("recording_started", "Recording Started"),
                            ("recording_stopped", "Recording Stopped"),
                            ("transcription_started", "Transcription Started"),
                            ("transcript_segment", "Transcript Segment"),
                            ("settings_changed", "Settings Changed"),
                            ("participant_muted", "Participant Muted"),
                            ("participant_unmuted", "Participant Unmuted"),
                            ("screen_share_started", "Screen Share Started"),
                            ("screen_share_stopped", "Screen Share Stopped"),
                            ("artifact_uploaded", "Artifact Uploaded"),
                            ("summary_generated", "Summary Generated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.CharField(
                        blank=True,
                        help_text="User or service that triggered event",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "data",
                    models.JSONField(default=dict, help_text="Event-specific data"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_events",
                "indexes": [
                    models.Index(
                        fields=["meeting", "created_at"],
                        name="meeting_eve_meeting_e37a1c_idx",
                    ),
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="meeting_eve_event_t_831dfb_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("drive", "Google Drive API"),
                            ("speech", "Google Speech-to-Text API"),
                            ("llm", "LLM Summarization API"),
                            ("websocket", "WebSocket"),
                            ("celery", "Celery Task"),
                            ("database", "Database"),
                            ("auth", "Authentication"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        default="error",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField()),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("stacktrace", models.TextField(blank=True)),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Additional context (user, meeting, etc)",
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_logs",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "error_logs",
                "indexes": [
                    models.Index(
                        fields=["meeting", "created_at"],
                        name="error_logs_meeting_436ed7_idx",
                    ),
                    models.Index(
                        fields=["error_type", "is_resolved"],
                        name="error_logs_error_t_d56bac_idx",
                    ),
                    models.Index(
                        fields=["severity", "is_resolved"],
                        name="error_logs_severit_10ef4b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="error_logs_created_008b9a_idx"
                    ),
                ],
            },
        ),
    ]
