# Generated by Django 4.2.15 on 2026-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemmetric",
            name="metric_type",
            field=models.CharField(
                choices=[
                    ("concurrent_events", "Concurrent events"),
                    ("concurrent_participants", "Concurrent Participants"),
                    ("api_response_time", "API Response Time"),
                    ("websocket_messages", "WebSocket Messages"),
                    ("celery_task_time", "Celery Task Time"),
                    ("drive_api_calls", "Drive API Calls"),
                    ("speech_api_calls", "Speech API Calls"),
                ],
                max_length=50,
            ),
        ),
    ]
