# Generated by Django 4.2.3 on 2026-08-26 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meeting_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drive_metadata_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.PositiveIntegerField(default=100)),
                ("allow_recording", models.BooleanField(default=False)),
                ("require_authentication", models.BooleanField(default=True)),
                ("meeting_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meetings",
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co-Host"),
                            ("presenter", "Presenter"),
                            ("attendee", "Attendee"),
                        ],
                        default="attendee",
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_video_on", models.BooleanField(default=False)),
                ("is_screen_sharing", models.BooleanField(default=False)),
                ("participant_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_participants",
                "indexes": [
                    models.Index(
                        fields=["meeting"], name="meeting_par_meeting_febdfc_idx"
                    ),
                    models.Index(
                        fields=["user"], name="meeting_par_user_id_025d70_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="meeting_par_is_acti_0545ef_idx"
                    ),
                ],
                "unique_together": {("meeting", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["meeting_code"], name="meetings_meeting_b1add0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["host"], name="meetings_host_id_e8c02e_idx"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(fields=["status"], name="meetings_status_85fffd_idx"),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["scheduled_start"], name="meetings_schedul_e67e75_idx"
            ),
        ),
    ]
