# Generated by Django 4.2.15 on 2026-09-17 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guest_sender_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "guest_recipient_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moderation_status",
                    models.CharField(
                        choices=[
                            ("not_required", "Not required"),
                            ("pending", "Awaiting host review"),
                            ("approved", "Approved by host"),
                            ("declined", "Declined by host"),
                            ("removed", "Removed by host"),
                        ],
                        default="not_required",
                        help_text="Direct messages from attendees are held for host review",
                        max_length=20,
                    ),
                ),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("none", "Not sorted"),
                            ("faq", "Question"),
                            ("suggestion", "Suggestion"),
                        ],
                        default="none",
                        help_text="Questions and suggestions the host has put on the board",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="answered_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("event_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                (
                    "drive_folder_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "drive_metadata_file_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scheduled_start", models.DateTimeField()),
                ("scheduled_end", models.DateTimeField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.PositiveIntegerField(default=100)),
                ("allow_recording", models.BooleanField(default=False)),
                ("require_authentication", models.BooleanField(default=True)),
                ("chat_enabled", models.BooleanField(default=False)),
                ("direct_messages_enabled", models.BooleanField(default=False)),
                ("event_metadata", models.JSONField(blank=True, default=dict)),
                ("guest_attendance", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hosted_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "events",
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GuestAttendee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for host"),
                            ("admitted", "Admitted"),
                            ("denied", "Denied"),
                            ("left", "Left"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_guest_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="meetings.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_guests",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HubPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("idea", "Idea"),
                            ("suggestion", "Suggestion to the organizer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("category", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In moderation"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("looking", "Being looked at"),
                            ("addressed", "Addressed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("answered_by", models.CharField(blank=True, max_length=255)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_posts",
                        to="meetings.event",
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_posts",
                        to="meetings.guestattendee",
                    ),
                ),
            ],
            options={
                "db_table": "hub_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("speaker_name", models.CharField(blank=True, max_length=255)),
                ("speaker_email", models.EmailField(blank=True, max_length=254)),
                ("speaker_phone", models.CharField(blank=True, max_length=40)),
                (
                    "speaker_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("hall", models.CharField(blank=True, max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="meetings.event",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "position"],
            },
        ),
        migrations.CreateModel(
            name="SessionSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                ("actions", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("needs_approval", "Needs approval"),
                            ("published", "Published"),
                        ],
                        default="needs_approval",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="meetings.session",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edited_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session_summaries",
                "ordering": ["session__starts_at"],
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "guest_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("marked_manually", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="session_attendance",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("co_host", "Co-host"), ("presenter", "Presenter")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="meetings.event",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "role_grants",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("event", "Event starting"),
                            ("session", "Session starting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("starts_at", models.DateTimeField()),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="meetings.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminders",
                "ordering": ["due_at"],
            },
        ),
        migrations.CreateModel(
            name="HubVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.SmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_votes",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="meetings.chatmessage",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="meetings.hubpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hub_votes",
            },
        ),
        migrations.AddField(
            model_name="hubpost",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hub_posts",
                to="meetings.session",
            ),
        ),
        migrations.AddField(
            model_name="hubpost",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hub_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View event"),
                            ("join", "Join event"),
                            ("record", "Record event"),
                            ("share_screen", "Share Screen"),
                            ("mute", "Mute Participants"),
                            ("remove", "Remove Participants"),
                            ("manage", "Manage event"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="meetings.event",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_permissions",
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("host", "Host"),
                            ("co_host", "Co-Host"),
                            ("presenter", "Presenter"),
                            ("attendee", "Attendee"),
                        ],
                        default="attendee",
                        max_length=20,
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=255, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_muted", models.BooleanField(default=False)),
                ("is_video_on", models.BooleanField(default=False)),
                ("is_screen_sharing", models.BooleanField(default=False)),
                ("participant_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="meetings.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_participants",
            },
        ),
        migrations.CreateModel(
            name="EventInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="meetings.event",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_event_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "joined_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_event_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "event_invites",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="meetings.event",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="guest_recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_chat_messages",
                to="meetings.guestattendee",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="guest_sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_chat_messages",
                to="meetings.guestattendee",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Null for a public room message",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guest__isnull", False), ("user__isnull", False), _negated=True
                ),
                name="session_attendance_exactly_one_attendee",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="session_attendance_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False)),
                fields=("session", "guest"),
                name="session_attendance_unique_guest",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["event", "starts_at"], name="meetings_se_event_i_67c8be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rolegrant",
            index=models.Index(fields=["email"], name="role_grants_email_de515a_idx"),
        ),
        migrations.AddIndex(
            model_name="rolegrant",
            index=models.Index(fields=["event"], name="role_grants_event_i_b1f5e7_idx"),
        ),
        migrations.AddIndex(
            model_name="rolegrant",
            index=models.Index(
                fields=["session"], name="role_grants_session_c3df9f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("event__isnull", False), ("session__isnull", True)),
                    models.Q(("event__isnull", True), ("session__isnull", False)),
                    _connector="OR",
                ),
                name="role_grant_has_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("email", "role", "event"),
                name="one_role_per_email_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("email", "role", "session"),
                name="one_role_per_email_per_session",
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["user", "due_at"], name="reminders_user_id_8edce6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reminder",
            index=models.Index(
                fields=["due_at", "delivered_at"], name="reminders_due_at_c58a45_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", True)),
                fields=("user", "event", "kind"),
                name="one_event_reminder_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("user", "session", "kind"),
                name="one_session_reminder_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("message__isnull", True), ("post__isnull", False)),
                    models.Q(("message__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="hub_vote_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="hub_vote_exactly_one_voter",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.CheckConstraint(
                check=models.Q(("value__in", [1, -1])), name="hub_vote_is_up_or_down"
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False), ("user__isnull", False)),
                fields=("post", "user"),
                name="one_vote_per_person_per_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False), ("post__isnull", False)),
                fields=("post", "guest"),
                name="one_vote_per_guest_per_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message__isnull", False), ("user__isnull", False)),
                fields=("message", "user"),
                name="one_vote_per_person_per_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("guest__isnull", False), ("message__isnull", False)
                ),
                fields=("message", "guest"),
                name="one_vote_per_guest_per_message",
            ),
        ),
        migrations.AddIndex(
            model_name="hubpost",
            index=models.Index(
                fields=["event", "kind", "status"], name="hub_posts_event_i_ff9e2b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hubpost",
            index=models.Index(fields=["session"], name="hub_posts_session_67537d_idx"),
        ),
        migrations.AddConstraint(
            model_name="hubpost",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="hub_post_exactly_one_author",
            ),
        ),
        migrations.AddIndex(
            model_name="guestattendee",
            index=models.Index(
                fields=["event", "status"], name="event_guest_event_i_5768f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventpermission",
            index=models.Index(
                fields=["event", "permission"], name="event_permi_event_i_906e1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventpermission",
            index=models.Index(fields=["user"], name="event_permi_user_id_afc407_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="eventpermission",
            unique_together={("event", "user", "permission")},
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["user"], name="event_parti_user_id_c7562f_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(
                fields=["is_active"], name="event_parti_is_acti_e7c2dd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventparticipant",
            unique_together={("event", "user")},
        ),
        migrations.AddIndex(
            model_name="eventinvite",
            index=models.Index(
                fields=["event", "joined_at"], name="event_invit_event_i_19ec2a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventinvite",
            unique_together={("event", "email")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["code"], name="events_code_722de6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["host"], name="events_host_id_3677bd_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_status_8890b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["scheduled_start"], name="events_schedul_650d02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["host", "event_date"], name="events_host_id_896e5a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contactrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="contact_request_exactly_one_asker",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="contact_request_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False)),
                fields=("session", "guest"),
                name="contact_request_unique_guest",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["event", "created_at"], name="event_chat__event_i_c5c799_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["event", "recipient"], name="event_chat__event_i_3fce4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["event", "guest_recipient"],
                name="event_chat__event_i_c54539_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["event", "moderation_status"],
                name="event_chat__event_i_7848d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["event", "topic"], name="event_chat__event_i_7ffae6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guest_sender__isnull", False),
                    ("sender__isnull", False),
                    _negated=True,
                ),
                name="chat_message_exactly_one_sender",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guest_recipient__isnull", False),
                    ("recipient__isnull", False),
                    _negated=True,
                ),
                name="chat_message_single_recipient",
            ),
        ),
    ]
