# Generated by Django 4.2.15 on 2026-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="speaker_role",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
