# Generated by Django 4.2.15 on 2026-08-26 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Meeting"),
                            ("join", "Join Meeting"),
                            ("record", "Record Meeting"),
                            ("share_screen", "Share Screen"),
                            ("mute", "Mute Participants"),
                            ("remove", "Remove Participants"),
                            ("manage", "Manage Meeting"),
                        ],
                        max_length=50,
                    ),
                ),
                ("granted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permissions_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_permissions",
                "indexes": [
                    models.Index(
                        fields=["meeting", "permission"],
                        name="meeting_per_meeting_1f5e82_idx",
                    ),
                    models.Index(
                        fields=["user"], name="meeting_per_user_id_95614e_idx"
                    ),
                ],
                "unique_together": {("meeting", "user", "permission")},
            },
        ),
    ]
