# Generated by Django 4.2.15 on 2026-09-18 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_session_speaker_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="hall",
        ),
    ]
