# Generated by Django 4.2.15 on 2026-08-27 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0002_meetingpermission"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="chat_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="meeting",
            name="direct_messages_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for a public room message",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "meeting_chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["meeting", "created_at"],
                        name="meeting_cha_meeting_30a0fd_idx",
                    ),
                    models.Index(
                        fields=["meeting", "recipient"],
                        name="meeting_cha_meeting_668398_idx",
                    ),
                ],
            },
        ),
    ]
