# Generated by Django 4.2.15 on 2026-08-27 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "meetings",
            "0003_meeting_chat_enabled_meeting_direct_messages_enabled_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="moderated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("not_required", "Not required"),
                    ("pending", "Awaiting host review"),
                    ("approved", "Approved by host"),
                    ("declined", "Declined by host"),
                    ("removed", "Removed by host"),
                ],
                default="not_required",
                help_text="Direct messages from attendees are held for host review",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["meeting", "moderation_status"],
                name="meeting_cha_meeting_d87ed7_idx",
            ),
        ),
    ]
