# Generated by Django 4.2.15 on 2026-09-22 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0003_remove_session_hall"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages",
                to="meetings.session",
            ),
        ),
    ]
