# Generated by Django 4.2.15 on 2026-09-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0004_chatmessage_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
