# Generated by Django 4.2.15 on 2026-08-27 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0004_chatmessage_moderated_at_chatmessage_moderated_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestAttendee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for host"),
                            ("admitted", "Admitted"),
                            ("denied", "Denied"),
                            ("left", "Left"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_guest_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guests",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_guests",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["meeting", "status"],
                        name="meeting_gue_meeting_b84bfa_idx",
                    )
                ],
            },
        ),
    ]
