# Generated by Django 4.2.15 on 2026-09-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0005_eventparticipant_last_seen_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="guestattendee",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="guestattendee",
            name="left_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
