# Generated by Django 4.2.15 on 2026-08-27 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0005_guestattendee"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingInvite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_meeting_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "joined_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_meeting_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invites",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_invites",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["meeting", "joined_at"],
                        name="meeting_inv_meeting_304ee5_idx",
                    )
                ],
                "unique_together": {("meeting", "email")},
            },
        ),
    ]
