# Generated by Django 4.2.15 on 2026-08-27 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0006_meetinginvite"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="guest_recipient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_chat_messages",
                to="meetings.guestattendee",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="guest_sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_chat_messages",
                to="meetings.guestattendee",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["meeting", "guest_recipient"],
                name="meeting_cha_meeting_8437e7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest_sender__isnull", True), ("sender__isnull", False)),
                    models.Q(("guest_sender__isnull", False), ("sender__isnull", True)),
                    _connector="OR",
                ),
                name="chat_message_exactly_one_sender",
            ),
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guest_recipient__isnull", False),
                    ("recipient__isnull", False),
                    _negated=True,
                ),
                name="chat_message_single_recipient",
            ),
        ),
    ]
