# Generated by Django 4.2.15 on 2026-09-23 12:07

from django.db import migrations, models
import django.db.models.deletion
import src.apps.meetings.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0006_guestattendee_last_seen_at_guestattendee_left_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("position", models.CharField(blank=True, max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=src.apps.meetings.models.speaker_photo_path,
                    ),
                ),
                ("linkedin_url", models.URLField(blank=True, max_length=500)),
                ("website_url", models.URLField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="meetings.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_speakers",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="speaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="meetings.speaker",
            ),
        ),
        migrations.AddIndex(
            model_name="speaker",
            index=models.Index(fields=["event"], name="event_speak_event_i_e67512_idx"),
        ),
    ]
