# Generated by Django 4.2.15 on 2026-09-03 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "meetings",
            "0007_chatmessage_guest_recipient_chatmessage_guest_sender_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("speaker_name", models.CharField(blank=True, max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("done", "Done"),
                            ("skipped", "Skipped"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "position"],
            },
        ),
        migrations.CreateModel(
            name="SessionAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("marked_manually", models.BooleanField(default=False)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attendance",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("venue", models.CharField(blank=True, max_length=255)),
                ("event_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-event_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="meeting",
            name="event",
            field=models.ForeignKey(
                blank=True,
                help_text="The programme this meeting belongs to, if any.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="meetings.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="session_attendance_exactly_one_attendee",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="session_attendance_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False)),
                fields=("session", "guest"),
                name="session_attendance_unique_guest",
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["meeting", "starts_at"], name="meetings_se_meeting_7d070b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["organizer", "event_date"],
                name="meetings_ev_organiz_d9e1bd_idx",
            ),
        ),
    ]
