# Generated by Django 4.2.15 on 2026-09-29 06:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0007_speaker_session_speaker_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_events",
                        to="meetings.event",
                    ),
                ),
            ],
            options={
                "db_table": "event_sub_events",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="session",
            name="sub_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sessions",
                to="meetings.subevent",
            ),
        ),
        migrations.AddIndex(
            model_name="subevent",
            index=models.Index(fields=["event"], name="event_sub_e_event_i_91b944_idx"),
        ),
    ]
