# Generated by Django 4.2.15 on 2026-09-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0008_session_sessionattendance_event_meeting_event_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="hall",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
