# Generated by Django 4.2.15 on 2026-10-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0008_subevent_session_sub_event_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hubpost",
            name="hub_post_exactly_one_author",
        ),
        migrations.AddField(
            model_name="hubpost",
            name="guest_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="hubpost",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hub_posts",
                to="meetings.guestattendee",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubpost",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    models.Q(
                        ("guest__isnull", True),
                        ("guest_name__gt", ""),
                        ("user__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="hub_post_exactly_one_author",
            ),
        ),
    ]
