# Generated by Django 4.2.15 on 2026-09-04 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0009_session_hall"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="speaker_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="session",
            name="speaker_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="session",
            name="speaker_visibility",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="private",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contact_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="contactrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="contact_request_exactly_one_asker",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="contact_request_unique_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="contactrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False)),
                fields=("session", "guest"),
                name="contact_request_unique_guest",
            ),
        ),
    ]
