# Generated by Django 4.2.15 on 2026-09-07 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0010_session_speaker_email_session_speaker_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=[("co_host", "Co-host"), ("presenter", "Presenter")],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="meetings.event",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "role_grants",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="role_grants_email_de515a_idx"),
                    models.Index(
                        fields=["event"], name="role_grants_event_i_b1f5e7_idx"
                    ),
                    models.Index(
                        fields=["meeting"], name="role_grants_meeting_c79971_idx"
                    ),
                    models.Index(
                        fields=["session"], name="role_grants_session_c3df9f_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("event__isnull", False),
                        ("meeting__isnull", True),
                        ("session__isnull", True),
                    ),
                    models.Q(
                        ("event__isnull", True),
                        ("meeting__isnull", False),
                        ("session__isnull", True),
                    ),
                    models.Q(
                        ("event__isnull", True),
                        ("meeting__isnull", True),
                        ("session__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="role_grant_has_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("email", "role", "event"),
                name="one_role_per_email_per_event",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("meeting__isnull", False)),
                fields=("email", "role", "meeting"),
                name="one_role_per_email_per_meeting",
            ),
        ),
        migrations.AddConstraint(
            model_name="rolegrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("email", "role", "session"),
                name="one_role_per_email_per_session",
            ),
        ),
    ]
