# Generated by Django 4.2.15 on 2026-09-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0011_role_grants"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="topic",
            field=models.CharField(
                choices=[
                    ("none", "Not sorted"),
                    ("faq", "Question"),
                    ("suggestion", "Suggestion"),
                ],
                default="none",
                help_text="Questions and suggestions the host has put on the board",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["meeting", "topic"], name="meeting_cha_meeting_13f80a_idx"
            ),
        ),
    ]
