# Generated by Django 4.2.15 on 2026-09-07 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0013_session_summary"),
    ]

    operations = [
        migrations.CreateModel(
            name="HubPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anonymous", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("question", "Question"),
                            ("idea", "Idea"),
                            ("suggestion", "Suggestion to the organizer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("body", models.TextField()),
                ("category", models.CharField(blank=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "In moderation"),
                            ("published", "Published"),
                            ("declined", "Declined"),
                            ("looking", "Being looked at"),
                            ("addressed", "Addressed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("answer", models.TextField(blank=True)),
                ("answered_by", models.CharField(blank=True, max_length=255)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_posts",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_posts",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hub_posts",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hub_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HubVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.SmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "guest",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_votes",
                        to="meetings.guestattendee",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="meetings.hubpost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hub_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hub_votes",
            },
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="hub_vote_exactly_one_voter",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.CheckConstraint(
                check=models.Q(("value__in", [1, -1])), name="hub_vote_is_up_or_down"
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("post", "user"),
                name="one_vote_per_person_per_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False)),
                fields=("post", "guest"),
                name="one_vote_per_guest_per_post",
            ),
        ),
        migrations.AddIndex(
            model_name="hubpost",
            index=models.Index(
                fields=["meeting", "kind", "status"],
                name="hub_posts_meeting_cad26b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hubpost",
            index=models.Index(fields=["session"], name="hub_posts_session_67537d_idx"),
        ),
        migrations.AddConstraint(
            model_name="hubpost",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("guest__isnull", True), ("user__isnull", False)),
                    models.Q(("guest__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="hub_post_exactly_one_author",
            ),
        ),
    ]
