# Generated by Django 4.2.15 on 2026-09-08 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0015_message_answer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="hubvote",
            name="one_vote_per_person_per_post",
        ),
        migrations.RemoveConstraint(
            model_name="hubvote",
            name="one_vote_per_guest_per_post",
        ),
        migrations.AddField(
            model_name="hubvote",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="meetings.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="hubvote",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="meetings.hubpost",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("message__isnull", True), ("post__isnull", False)),
                    models.Q(("message__isnull", False), ("post__isnull", True)),
                    _connector="OR",
                ),
                name="hub_vote_exactly_one_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("post__isnull", False), ("user__isnull", False)),
                fields=("post", "user"),
                name="one_vote_per_person_per_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("guest__isnull", False), ("post__isnull", False)),
                fields=("post", "guest"),
                name="one_vote_per_guest_per_post",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("message__isnull", False), ("user__isnull", False)),
                fields=("message", "user"),
                name="one_vote_per_person_per_message",
            ),
        ),
        migrations.AddConstraint(
            model_name="hubvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("guest__isnull", False), ("message__isnull", False)
                ),
                fields=("message", "guest"),
                name="one_vote_per_guest_per_message",
            ),
        ),
    ]
