# Generated by Django 4.2.15 on 2026-09-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meetings", "0016_board_votes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting starting"),
                            ("session", "Session starting"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField()),
                ("starts_at", models.DateTimeField()),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="meetings.session",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminders",
                "ordering": ["due_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "due_at"], name="reminders_user_id_8edce6_idx"
                    ),
                    models.Index(
                        fields=["due_at", "delivered_at"],
                        name="reminders_due_at_c58a45_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", True)),
                fields=("user", "meeting", "kind"),
                name="one_meeting_reminder_per_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="reminder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("session__isnull", False)),
                fields=("user", "session", "kind"),
                name="one_session_reminder_per_person",
            ),
        ),
    ]
