# Generated by Django 4.2.15 on 2026-09-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0017_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionsummary",
            name="actions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
