# Generated by Django 4.2.15 on 2026-09-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0018_sessionsummary_actions"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sessionattendance",
            name="session_attendance_exactly_one_attendee",
        ),
        migrations.AddField(
            model_name="sessionattendance",
            name="guest_name",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AlterField(
            model_name="guestattendee",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="sessionattendance",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_attendance",
                to="meetings.guestattendee",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionattendance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guest__isnull", False), ("user__isnull", False), _negated=True
                ),
                name="session_attendance_exactly_one_attendee",
            ),
        ),
    ]
