# Generated by Django 4.2.15 on 2026-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "meetings",
            "0019_remove_sessionattendance_session_attendance_exactly_one_attendee_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="guest_attendance",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
