# Generated by Django 4.2.15 on 2026-09-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0021_chatmessage_guest_recipient_name_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatmessage",
            name="chat_message_exactly_one_sender",
        ),
        migrations.AddConstraint(
            model_name="chatmessage",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("guest_sender__isnull", False),
                    ("sender__isnull", False),
                    _negated=True,
                ),
                name="chat_message_exactly_one_sender",
            ),
        ),
    ]
